name: Deploy Streamlit App

on:
  push:
    branches: [main] 
    # Or your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Check (optional)
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

    - name: Deploy to Streamlit (manual step)
      run: echo "Please deploy manually via Streamlit Cloud: https://streamlit.io/cloud"
